import { StyleSheet } from 'react-native';
import type { useTheme } from '@/shared/theme';

export function createStyles(t: ReturnType<typeof useTheme>) {
  return StyleSheet.create({
    screenWrapper: {
      flex: 1,
      backgroundColor: t.colors.background,
    },
    headerAddBtn: {
      borderRadius: 12,
      overflow: 'hidden',
    },
    headerAddGradient: {
      width: 36,
      height: 36,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    listContent: {
      paddingHorizontal: t.spacing.lg,
      paddingTop: t.spacing.md,
      paddingBottom: 120,
    },
    headerBlock: {
      marginBottom: t.spacing.md,
    },
    heroCard: {
      position: 'relative',
      backgroundColor: t.colors.surfaceContainer ?? t.colors.surface,
      borderRadius: t.radii.card ?? 20,
      padding: 20,
      borderWidth: 1,
      borderColor: t.isDark ? 'rgba(255,255,255,0.06)' : t.colors.borderSubtle,
      overflow: 'hidden',
      marginBottom: t.spacing.md,
    },
    heroGlowCircle: {
      position: 'absolute',
      top: -40,
      right: -40,
      width: 160,
      height: 160,
      borderRadius: 80,
      backgroundColor: 'rgba(78, 222, 163, 0.10)',
    },
    heroHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 16,
    },
    heroTitleCluster: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    heroIconPod: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: t.isDark ? 'rgba(78, 222, 163, 0.15)' : 'rgba(78, 222, 163, 0.25)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    heroTitle: {
      ...t.typography.bodySemibold,
      color: t.colors.text,
      fontSize: 15,
      fontWeight: '700',
    },
    activeTag: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: t.isDark ? 'rgba(78, 222, 163, 0.12)' : t.colors.secondaryContainer,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: t.isDark ? 'rgba(78, 222, 163, 0.28)' : 'transparent',
    },
    pulseDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: t.colors.secondary,
    },
    activeTagText: {
      fontSize: 11,
      fontWeight: '700',
      color: t.colors.secondary,
    },
    heroBody: {
      marginBottom: 14,
    },
    heroLabel: {
      ...t.typography.label,
      color: t.colors.textTertiary,
      fontSize: 11,
      textTransform: 'uppercase',
      letterSpacing: 0.6,
      marginBottom: 4,
    },
    heroAmount: {
      ...t.typography.amount,
      fontSize: 32,
      fontWeight: '800',
      color: t.colors.text,
      letterSpacing: -0.8,
    },
    heroFooter: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    statPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: t.isDark ? 'rgba(78, 222, 163, 0.08)' : 'rgba(78, 222, 163, 0.15)',
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 8,
    },
    statPillText: {
      fontSize: 12,
      fontWeight: '500',
      color: t.colors.textSecondary,
    },
    sourcesSection: {
      marginTop: 4,
      marginBottom: 8,
    },
    sectionHeaderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: t.spacing.sm,
      marginBottom: t.spacing.xs,
    },
    sectionLabel: {
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.8,
      color: t.colors.textTertiary,
    },
    sourcesCountText: {
      fontSize: 11,
      color: t.colors.textTertiary,
      fontWeight: '500',
    },
    sourcesScroll: {
      gap: 10,
      paddingVertical: 6,
    },
    filterChipsWrap: {
      marginTop: t.spacing.sm * 2,
    },
    sourceCard: {
      width: 130,
      backgroundColor: t.colors.surfaceContainer ?? t.colors.surface,
      borderRadius: 16,
      padding: 12,
      borderWidth: 1,
      borderColor: t.isDark ? 'rgba(255,255,255,0.06)' : t.colors.borderSubtle,
    },
    sourceCardIconPod: {
      width: 30,
      height: 30,
      borderRadius: 8,
      backgroundColor: t.isDark ? 'rgba(14, 165, 233, 0.12)' : 'rgba(14, 165, 233, 0.15)',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 8,
    },
    sourceName: {
      ...t.typography.bodySemibold,
      color: t.colors.text,
      fontSize: 13,
      fontWeight: '700',
      marginBottom: 4,
    },
    sourceTypePill: {
      alignSelf: 'flex-start',
      backgroundColor: t.isDark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.04)',
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 4,
    },
    sourceType: {
      ...t.typography.caption,
      color: t.colors.textSecondary,
      textTransform: 'capitalize',
      fontSize: 10,
      fontWeight: '600',
    },
    sectionTitle: {
      ...t.typography.titleSm,
      fontSize: 17,
      fontWeight: '700',
      color: t.colors.text,
    },
    sectionCount: {
      ...t.typography.caption,
      color: t.colors.textTertiary,
      fontWeight: '600',
    },
    separator: {
      height: 8,
    },
    footerWrap: {
      marginTop: t.spacing.lg,
    },
    createBtnWrap: {
      borderRadius: 14,
      overflow: 'hidden',
    },
    createBtnGradient: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingVertical: 14,
      paddingHorizontal: 20,
    },
    createBtnText: {
      fontSize: 15,
      fontWeight: '700',
      color: '#003824',
      letterSpacing: -0.2,
    },
  });
}
