import { StyleSheet } from 'react-native';
import type { useTheme } from '@/shared/theme';

export function createStyles(t: ReturnType<typeof useTheme>) {
  return StyleSheet.create({
    container: {
      gap: t.spacing.md,
      marginBottom: t.spacing.sm,
    },
    heroCard: {
      backgroundColor: t.colors.surface,
      borderRadius: t.radii.xl,
      padding: t.spacing.lg,
      borderWidth: 1,
      borderColor: t.colors.borderSubtle,
      ...t.shadows.md,
      position: 'relative',
      overflow: 'hidden',
    },
    ambientGlowRight: {
      position: 'absolute',
      top: -40,
      right: -40,
      width: 130,
      height: 130,
      borderRadius: 65,
      backgroundColor: t.colors.primary + '16',
    },
    ambientGlowLeft: {
      position: 'absolute',
      bottom: -40,
      left: -40,
      width: 120,
      height: 120,
      borderRadius: 60,
      backgroundColor: t.colors.violet + '14',
    },
    heroContent: {
      gap: t.spacing.md,
    },
    topStatusRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    greetingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    livePulseContainer: {
      width: 10,
      height: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    livePulseDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
    },
    greetingText: {
      fontSize: 13,
      fontWeight: '500',
      color: t.colors.textSecondary,
    },
    savingsChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: t.radii.full,
      backgroundColor: t.colors.secondary + '1C',
    },
    savingsChipText: {
      fontSize: 11,
      fontWeight: '700',
      color: t.colors.secondary,
    },
    middleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    amountCol: {
      flex: 1,
      gap: 4,
    },
    amountLabel: {
      fontSize: 11,
      fontWeight: '600',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
      color: t.colors.textTertiary,
    },
    amountText: {
      fontSize: 30,
      fontWeight: '800',
      letterSpacing: -0.8,
      color: t.colors.text,
      fontVariant: ['tabular-nums'],
      fontFamily: t.typography.display.fontFamily,
    },
    skeletonWrap: {
      paddingVertical: 4,
    },
    targetBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingTop: 4,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: t.colors.borderSubtle,
    },
    targetLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      flex: 1,
    },
    targetText: {
      fontSize: 12,
      fontWeight: '500',
      color: t.colors.textSecondary,
    },
    targetDaysLeft: {
      fontSize: 12,
      fontWeight: '600',
      color: t.colors.primary,
    },
    quickActionsGrid: {
      flexDirection: 'row',
      gap: t.spacing.sm,
    },
    actionPressable: {
      flex: 1,
    },
    actionPressed: {
      transform: [{ scale: 0.96 }],
      opacity: 0.9,
    },
    actionPrimaryGradient: {
      paddingVertical: 12,
      paddingHorizontal: 8,
      borderRadius: t.radii.md,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      ...t.shadows.sm,
    },
    actionPrimaryIconCircle: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: 'rgba(255,255,255,0.22)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    actionPrimaryLabel: {
      fontSize: 12,
      fontWeight: '700',
      color: '#FFFFFF',
    },
    actionSecondaryBtn: {
      paddingVertical: 12,
      paddingHorizontal: 8,
      borderRadius: t.radii.md,
      backgroundColor: t.colors.surface,
      borderWidth: 1,
      borderColor: t.colors.borderSubtle,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      ...t.shadows.sm,
    },
    actionSecondaryIconCircle: {
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    actionSecondaryLabel: {
      fontSize: 12,
      fontWeight: '600',
      color: t.colors.text,
    },
  });
}
