import { StyleSheet } from 'react-native';
import type { useTheme } from '@/shared/theme';

export function createStyles(t: ReturnType<typeof useTheme>) {
  return StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.65)',
      justifyContent: 'flex-end',
    },
    sheetContainer: {
      backgroundColor: t.colors.surfaceContainer ?? t.colors.surface,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      paddingHorizontal: t.spacing.lg,
      paddingTop: 16,
      paddingBottom: 36,
      maxHeight: '92%',
      borderTopWidth: 1,
      borderColor: t.isDark ? 'rgba(255,255,255,0.1)' : t.colors.borderSubtle,
    },
    dragHandle: {
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: t.isDark ? 'rgba(255,255,255,0.2)' : 'rgba(0,0,0,0.2)',
      alignSelf: 'center',
      marginBottom: 16,
    },
    headerRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      marginBottom: 12,
    },
    badgePod: {
      backgroundColor: t.colors.primary,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 8,
      alignSelf: 'flex-start',
    },
    badgeText: {
      color: '#FFFFFF',
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 0.8,
    },
    closeBtn: {
      padding: 6,
      borderRadius: 20,
      backgroundColor: t.isDark ? 'rgba(255,255,255,0.08)' : 'rgba(0,0,0,0.05)',
    },
    closeText: {
      color: t.colors.textSecondary,
      fontSize: 16,
      fontWeight: '600',
    },
    title: {
      ...t.typography.title,
      fontSize: 22,
      fontWeight: '800',
      color: t.colors.text,
      marginTop: 8,
      marginBottom: 6,
    },
    subtitle: {
      ...t.typography.body,
      fontSize: 13,
      color: t.colors.textSecondary,
      lineHeight: 18,
      marginBottom: 20,
    },
    featureList: {
      gap: 12,
      marginBottom: 22,
    },
    featureItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    featureCheckPod: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: t.isDark ? 'rgba(16, 185, 129, 0.2)' : 'rgba(16, 185, 129, 0.15)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    featureText: {
      ...t.typography.body,
      fontSize: 13,
      fontWeight: '500',
      color: t.colors.text,
      flex: 1,
    },
    planList: {
      gap: 10,
      marginBottom: 20,
    },
    planCard: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 16,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: t.isDark ? 'rgba(255,255,255,0.1)' : t.colors.borderSubtle,
      backgroundColor: t.colors.surface,
    },
    planCardSelected: {
      borderColor: t.colors.primary,
      backgroundColor: t.isDark ? 'rgba(14, 165, 233, 0.08)' : 'rgba(14, 165, 233, 0.04)',
    },
    planLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    radioCircle: {
      width: 20,
      height: 20,
      borderRadius: 10,
      borderWidth: 2,
      borderColor: t.colors.textTertiary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    radioCircleActive: {
      borderColor: t.colors.primary,
    },
    radioInner: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: t.colors.primary,
    },
    planTitle: {
      ...t.typography.bodySemibold,
      fontSize: 14,
      color: t.colors.text,
    },
    planTag: {
      fontSize: 10,
      fontWeight: '700',
      color: t.colors.primary,
      marginTop: 2,
    },
    planPrice: {
      ...t.typography.bodySemibold,
      fontSize: 15,
      color: t.colors.text,
      fontWeight: '700',
    },
    planSubtext: {
      fontSize: 11,
      color: t.colors.textTertiary,
      textAlign: 'right',
    },
    ctaButton: {
      backgroundColor: t.colors.primary,
      paddingVertical: 14,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: t.colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 4,
    },
    ctaText: {
      color: '#FFFFFF',
      fontSize: 15,
      fontWeight: '700',
      letterSpacing: 0.3,
    },
    legalText: {
      ...t.typography.caption,
      color: t.colors.textTertiary,
      fontSize: 11,
      textAlign: 'center',
      marginTop: 4,
      lineHeight: 14,
    },
  });
}
