import { StyleSheet } from 'react-native';
import type { useTheme } from '@/shared/theme';

export function scrollBottomInset(bottomSafe: number, spacingLg: number) {
  return { paddingBottom: bottomSafe + spacingLg };
}

export function categoryIconTint(color: string) {
  return { backgroundColor: color + '22' };
}

export function createStyles(t: ReturnType<typeof useTheme>) {
  return StyleSheet.create({
    screenWrapper: {
      flex: 1,
      backgroundColor: t.colors.background,
    },
    scrollContent: {
      paddingHorizontal: t.spacing.lg,
      gap: t.spacing.lg,
    },
    sheetHeader: {
      alignItems: 'center',
      gap: 12,
      paddingTop: 8,
    },
    sheetHandle: {
      width: 40,
      height: 4,
      borderRadius: 2,
      backgroundColor: t.colors.surfaceBright,
    },
    sheetTitleRow: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    sheetTitleLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    sheetIconPod: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: t.colors.primary + '20',
      alignItems: 'center',
      justifyContent: 'center',
    },
    sheetEyebrow: {
      fontSize: 10,
      fontWeight: '600',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
      color: t.colors.textTertiary,
    },
    sheetTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: t.colors.text,
      letterSpacing: -0.3,
    },
    sheetActionsRight: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    scanReceiptBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: t.radii.full,
      backgroundColor: t.colors.surfaceContainerHigh,
    },
    scanReceiptText: {
      fontSize: 12,
      fontWeight: '600',
      color: t.colors.primary,
    },
    closeBtn: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: t.colors.surfaceContainerHigh,
      alignItems: 'center',
      justifyContent: 'center',
    },
    amountHeroCard: {
      backgroundColor: t.colors.surfaceContainerLow,
      borderRadius: t.radii.card,
      padding: t.spacing.lg,
      borderWidth: 1,
      borderColor: t.colors.borderSubtle,
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
      overflow: 'hidden',
      ...t.shadows.sm,
    },
    glowTopRight: {
      position: 'absolute',
      top: -30,
      right: -30,
      width: 100,
      height: 100,
      borderRadius: 50,
      backgroundColor: t.colors.primary + '14',
    },
    glowBottomLeft: {
      position: 'absolute',
      bottom: -30,
      left: -30,
      width: 100,
      height: 100,
      borderRadius: 50,
      backgroundColor: t.colors.secondary + '14',
    },
    amountTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 10,
    },
    currencyTogglePill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: t.radii.full,
      backgroundColor: t.colors.surface,
    },
    currencySymbol: {
      fontSize: 13,
      fontWeight: '700',
      color: t.colors.text,
    },
    currencyCode: {
      fontSize: 11,
      fontWeight: '600',
      color: t.colors.textTertiary,
    },
    amountSpentLabel: {
      fontSize: 12,
      color: t.colors.textTertiary,
    },
    heroAmountRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    heroSymbolText: {
      fontSize: 28,
      fontWeight: '800',
      color: t.colors.textTertiary,
      marginRight: 4,
    },
    heroAmountInput: {
      fontSize: 32,
      fontWeight: '800',
      color: t.colors.text,
      fontVariant: ['tabular-nums'],
      minWidth: 120,
      textAlign: 'center',
    },
    presetChipsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: 14,
      flexWrap: 'wrap',
      justifyContent: 'center',
    },
    presetChip: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: t.radii.full,
      backgroundColor: t.colors.surfaceContainerHigh,
    },
    roundUpChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    presetPressed: {
      transform: [{ scale: 0.94 }],
      opacity: 0.8,
    },
    presetText: {
      fontSize: 12,
      fontWeight: '600',
      color: t.colors.text,
    },
    presetTextSecondary: {
      color: t.colors.secondary,
    },
    sectionWrap: {
      gap: 8,
    },
    sectionEyebrow: {
      fontSize: 11,
      fontWeight: '600',
      letterSpacing: 0.4,
      textTransform: 'uppercase',
      color: t.colors.textTertiary,
    },
    sectionHeaderBetween: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    suggestedHint: {
      fontSize: 11,
      fontWeight: '600',
      color: t.colors.primary,
    },
    merchantInputWrap: {
      height: 48,
      borderRadius: t.radii.md,
      backgroundColor: t.colors.surfaceContainerLow,
      borderWidth: 1,
      borderColor: t.colors.borderSubtle,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 14,
      gap: 10,
    },
    merchantInput: {
      flex: 1,
      fontSize: 14,
      color: t.colors.text,
    },
    merchantRail: {
      paddingTop: 4,
    },
    merchantChip: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: t.radii.full,
      backgroundColor: t.colors.surface,
      marginRight: 8,
    },
    merchantChipText: {
      fontSize: 12,
      color: t.colors.textSecondary,
      fontWeight: '500',
    },
    categoryGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      justifyContent: 'space-between',
    },
    categoryTile: {
      width: '23%',
      paddingVertical: 10,
      paddingHorizontal: 4,
      borderRadius: t.radii.md,
      backgroundColor: t.colors.surfaceContainerLow,
      borderWidth: 1,
      borderColor: t.colors.borderSubtle,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    categoryTileSelected: {
      backgroundColor: t.colors.surfaceContainerHigh,
      borderColor: t.colors.primary,
    },
    catIconCircle: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
    },
    catTileLabel: {
      fontSize: 11,
      fontWeight: '500',
      color: t.colors.textSecondary,
      textAlign: 'center',
    },
    catTileLabelSelected: {
      color: t.colors.text,
      fontWeight: '700',
    },
    paymentMethodsRow: {
      flexDirection: 'row',
      gap: 8,
      backgroundColor: t.colors.surfaceContainerLow,
      padding: 6,
      borderRadius: t.radii.md,
    },
    payMethodTile: {
      flex: 1,
      paddingVertical: 8,
      borderRadius: t.radii.sm,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
    },
    payMethodTileSelected: {
      backgroundColor: t.colors.surfaceContainerHigh,
    },
    payMethodLabel: {
      fontSize: 11,
      fontWeight: '600',
      color: t.colors.textSecondary,
    },
    payMethodLabelSelected: {
      color: t.colors.primary,
      fontWeight: '700',
    },
    infoCardRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 14,
      borderRadius: t.radii.md,
      backgroundColor: t.colors.surfaceContainerLow,
      borderWidth: 1,
      borderColor: t.colors.borderSubtle,
    },
    infoCardRowSpaced: {
      marginTop: 8,
    },
    infoCardLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      flex: 1,
    },
    infoIconCircle: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    infoIconCirclePrimary: {
      backgroundColor: t.colors.primary + '18',
    },
    infoIconCircleSecondary: {
      backgroundColor: t.colors.secondary + '18',
    },
    infoCardTitle: {
      fontSize: 13,
      fontWeight: '600',
      color: t.colors.text,
    },
    infoCardSub: {
      fontSize: 11,
      color: t.colors.textTertiary,
    },
    changeActionBtn: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: t.radii.full,
      backgroundColor: t.colors.surface,
    },
    changeActionText: {
      fontSize: 11,
      fontWeight: '600',
      color: t.colors.textSecondary,
    },
    datePickerWrap: {
      marginTop: 8,
    },
    receiptUploadCard: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 14,
      borderRadius: t.radii.md,
      backgroundColor: t.colors.surfaceContainerLow,
      borderWidth: 1,
      borderColor: t.colors.borderSubtle,
    },
    receiptLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      flex: 1,
    },
    receiptIconCircle: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: t.colors.primary + '18',
      alignItems: 'center',
      justifyContent: 'center',
    },
    receiptTextCol: { flex: 1 },
    receiptTitle: {
      fontSize: 13,
      fontWeight: '600',
      color: t.colors.text,
    },
    receiptSub: {
      fontSize: 11,
      color: t.colors.textTertiary,
    },
    receiptThumb: {
      width: 36,
      height: 36,
      borderRadius: 8,
    },
    notesBox: {
      borderRadius: t.radii.md,
      backgroundColor: t.colors.surfaceContainerLow,
      borderWidth: 1,
      borderColor: t.colors.borderSubtle,
      padding: 12,
      gap: 10,
    },
    notesInput: {
      fontSize: 13,
      color: t.colors.text,
      minHeight: 32,
    },
    tagChipsRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flexWrap: 'wrap',
    },
    tagChip: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: t.radii.full,
      backgroundColor: t.colors.surface,
    },
    tagChipSelected: {
      backgroundColor: t.colors.primary + '22',
    },
    tagChipText: {
      fontSize: 11,
      fontWeight: '500',
      color: t.colors.textSecondary,
    },
    tagChipTextSelected: {
      color: t.colors.primary,
      fontWeight: '700',
    },
    optionalText: {
      fontSize: 11,
      color: t.colors.textTertiary,
    },
    fieldErrorText: {
      fontSize: 11,
      color: t.colors.danger,
      marginTop: 2,
    },
    saveBtnWrap: {
      paddingTop: 8,
      paddingBottom: t.spacing.sm,
    },
    pressedFade: { opacity: 0.85 },
    pressedChip: { opacity: 0.8 },
    tilePressed: { transform: [{ scale: 0.96 }] },
    savePressable: {
      width: '100%',
      borderRadius: t.radii.full,
      overflow: 'hidden',
      ...t.shadows.md,
    },
    savePressablePressed: {
      transform: [{ scale: 0.98 }],
    },
    savePressableDisabled: {
      opacity: 0.7,
    },
    saveGradient: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingVertical: 16,
    },
    saveButtonText: {
      fontSize: 15,
      fontWeight: '700',
      color: '#FFFFFF',
    },
  });
}
