import { StyleSheet } from 'react-native';
import type { useTheme } from '@/shared/theme';

export function createStyles(t: ReturnType<typeof useTheme>) {
  return StyleSheet.create({
    screenWrapper: {
      flex: 1,
      backgroundColor: t.colors.background,
    },
    listContent: {
      paddingHorizontal: t.spacing.lg,
    },
    headerBlock: {
      gap: t.spacing.md,
      paddingVertical: t.spacing.md,
    },
    radialGaugeCard: {
      backgroundColor: t.colors.surfaceContainerHigh,
      borderRadius: t.radii.card,
      padding: t.spacing.lg,
      borderWidth: 1,
      borderColor: t.colors.borderSubtle,
      ...t.shadows.md,
      position: 'relative',
      overflow: 'hidden',
      gap: t.spacing.md,
    },
    glowTopRight: {
      position: 'absolute',
      top: -40,
      right: -40,
      width: 120,
      height: 120,
      borderRadius: 60,
      backgroundColor: t.colors.primary + '18',
    },
    glowBottomLeft: {
      position: 'absolute',
      bottom: -40,
      left: -40,
      width: 110,
      height: 110,
      borderRadius: 55,
      backgroundColor: t.colors.violet + '14',
    },
    gaugeHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    gaugeTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    gaugeTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: t.colors.text,
      letterSpacing: -0.2,
    },
    daysLeftTag: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: t.radii.full,
      backgroundColor: t.colors.surfaceContainerHighest,
    },
    pulseDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
    },
    daysLeftText: {
      fontSize: 11,
      fontWeight: '600',
      color: t.colors.textSecondary,
    },
    gaugeBodyRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: t.spacing.lg,
    },
    metricsCol: {
      flex: 1,
      gap: 2,
    },
    consumedLabel: {
      fontSize: 11,
      fontWeight: '600',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
      color: t.colors.textTertiary,
    },
    consumedAmountRow: {
      flexDirection: 'row',
      alignItems: 'baseline',
    },
    consumedAmountInteger: {
      fontSize: 28,
      fontWeight: '800',
      letterSpacing: -0.5,
      color: t.colors.text,
      fontVariant: ['tabular-nums'],
    },
    consumedAmountFraction: {
      fontSize: 17,
      fontWeight: '700',
      color: t.colors.textSecondary,
      fontVariant: ['tabular-nums'],
    },
    limitLabel: {
      fontSize: 12,
      color: t.colors.textTertiary,
      marginBottom: 6,
    },
    dailySafePill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: t.radii.sm,
      backgroundColor: t.colors.surfaceContainerLow,
    },
    dailySafeText: {
      fontSize: 11,
      color: t.colors.textSecondary,
    },
    dailySafeAmount: {
      fontWeight: '700',
      color: t.colors.secondaryFixed,
    },
    aiForecastCard: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
      padding: t.spacing.md,
      borderRadius: t.radii.card,
      backgroundColor: t.colors.surfaceContainerLow,
      borderWidth: 1,
      borderColor: t.colors.borderSubtle,
      ...t.shadows.sm,
    },
    aiIconCircle: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: t.colors.primary + '20',
      alignItems: 'center',
      justifyContent: 'center',
    },
    aiContentCol: {
      flex: 1,
      gap: 4,
    },
    aiTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: t.colors.text,
    },
    aiDescription: {
      fontSize: 12,
      color: t.colors.textSecondary,
      lineHeight: 18,
    },
    aiActionBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginTop: 4,
    },
    aiActionText: {
      fontSize: 12,
      fontWeight: '700',
      color: t.colors.primary,
    },
    categorySectionHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingTop: 4,
    },
    categoryTitleGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    categorySectionTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: t.colors.text,
    },
    syncTag: {
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: t.radii.full,
      backgroundColor: t.colors.surfaceContainerHigh,
    },
    syncTagText: {
      fontSize: 10,
      fontWeight: '600',
      color: t.colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.3,
    },
    sortBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: t.radii.sm,
      backgroundColor: t.colors.surfaceContainerHigh,
    },
    sortBtnText: {
      fontSize: 11,
      fontWeight: '600',
      color: t.colors.textSecondary,
    },
    cardItemWrap: {
      marginBottom: 10,
    },
    footerWrap: {
      paddingVertical: t.spacing.lg,
    },
    createBtnWrap: {
      width: '100%',
      borderRadius: t.radii.lg,
      overflow: 'hidden',
      ...t.shadows.md,
    },
    createBtnGradient: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingVertical: 14,
      paddingHorizontal: 16,
    },
    createBtnText: {
      fontSize: 15,
      fontWeight: '700',
      color: '#FFFFFF',
    },
  });
}
